//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosesApi.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOperationsEntities : DbContext
    {
        public DbOperationsEntities()
            : base("name=DbOperationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<City_User> City_User { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Operatopn_Doctor> Operatopn_Doctor { get; set; }
        public virtual DbSet<Organisation> Organisation { get; set; }
        public virtual DbSet<Organisation_User> Organisation_User { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserSession> UserSession { get; set; }
    }
}
