//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosesApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.City_User = new HashSet<City_User>();
            this.Operatopn_Doctor = new HashSet<Operatopn_Doctor>();
            this.Organisation = new HashSet<Organisation>();
            this.Organisation_User = new HashSet<Organisation_User>();
            this.UserSession = new HashSet<UserSession>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronimic { get; set; }
        public Nullable<bool> isDoctor { get; set; }
        public Nullable<int> rating { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<int> organisation_id { get; set; }
        public System.DateTime last_active { get; set; }
        public string website { get; set; }
        public string instagram { get; set; }
        public string facebook { get; set; }
        public string vk { get; set; }
        public string youtube { get; set; }
        public string twitter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City_User> City_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operatopn_Doctor> Operatopn_Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisation> Organisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisation_User> Organisation_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSession { get; set; }
    }
}
